function [Pt_out,Tt_out,W_out,ComprWork,Tt_out_Z1,Tt_out_Z2,Tt_out_Z3]=DesignCompressor(Pt_in,Tt_in,W_in,DesignData_Compressor,AirPlan)
%压气机设计点参数
d_Sigma_ComprIn=DesignData_Compressor(1);
d_Compr_PR=DesignData_Compressor(2);
d_Compr_Eff=DesignData_Compressor(3);
d_Compr_Z1=DesignData_Compressor(4);
d_Compr_Z2=DesignData_Compressor(5);
d_Compr_Z3=DesignData_Compressor(6);
d_Compr_Z=DesignData_Compressor(7);
%放气与冷却引气计划
Compr_Def_W=AirPlan(1);
HPT_Cool_NGV_W=AirPlan(2);
HPT_Cool_PT_W=AirPlan(3);
LPT_Cool_NGV_W=AirPlan(4);
LPT_Cool_PT_W=AirPlan(5);
%设计点压气机
h_in=gashi(Tt_in,0);
%第Z1级放气
d_Compr_PR_Z1=d_Compr_PR^(d_Compr_Z1/d_Compr_Z);
Tt_out_Z1=GasTt(Tt_in,0,d_Compr_PR_Z1,d_Compr_Eff);
h_Z1=gashi(Tt_out_Z1,0);
%第Z2级冷却引气
d_Compr_PR_Z2=d_Compr_PR^(d_Compr_Z2/d_Compr_Z);
Tt_out_Z2=GasTt(Tt_in,0,d_Compr_PR_Z2,d_Compr_Eff);
h_Z2=gashi(Tt_out_Z2,0);
%第Z3级冷却引气
d_Compr_PR_Z3=d_Compr_PR^(d_Compr_Z3/d_Compr_Z);
Tt_out_Z3=GasTt(Tt_in,0,d_Compr_PR_Z3,d_Compr_Eff);
h_Z3=gashi(Tt_out_Z3,0);
%压气机出口
Pt_out=Pt_in*d_Compr_PR*d_Sigma_ComprIn;
Tt_out=GasTt(Tt_in,0,d_Compr_PR,d_Compr_Eff);
h_out=gashi(Tt_out,0);
W_out=W_in*(1-Compr_Def_W-HPT_Cool_NGV_W-HPT_Cool_PT_W-LPT_Cool_NGV_W-LPT_Cool_PT_W);
ComprWork=W_in*((h_Z1-h_in)+(h_Z2-h_Z1)*(1-Compr_Def_W)+(h_Z3-h_Z2)*(1-Compr_Def_W-LPT_Cool_PT_W)+(h_out-h_Z3)*(1-Compr_Def_W-LPT_Cool_PT_W-LPT_Cool_NGV_W));